declare module "lucide-react" {
  export const Car: any
  export const ArrowLeft: any
  export const ArrowRight: any
  export const MapPin: any
  export const Fuel: any
  export const Gauge: any
  export const Calendar: any
  export const CalendarDays: any
  export const Menu: any
  export const X: any
  export const Search: any
  export const ShoppingCart: any
  export const Sparkles: any
  export const RotateCcw: any
  export const Phone: any
  export const Mail: any
  export const Clock: any
  export const Shield: any
  export const Users: any
  export const Award: any
  export const Heart: any
  export const CheckCircle: any
  export const Percent: any
  export const CreditCard: any
  export const ClipboardCheck: any
  export const DollarSign: any
  export const FileText: any
  export const Truck: any
  export const ChevronDown: any
  export const SlidersHorizontal: any
  export const Star: any
  export const Filter: any
  export const Plus: any
  export const Minus: any
  export const Trash2: any
  export const Edit: any
  export const Eye: any
  export const Settings: any
  export const Tag: any
  export const Grid: any
  export const List: any
  export const Check: any
  export const AlertCircle: any
  export const Info: any
  export const Home: any
  export const HelpCircle: any
  export const MessageSquare: any
  export const Send: any
  export const ChevronUp: any
  export const ChevronLeft: any
  export const ChevronRight: any
  export const Headphones: any
  export const Quote: any
  export const MapPin: any
}
